# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f27308f68c2e5564595e534d1a8e140a337d192151e01b5a1d40bfe39f44bf1cbcbbf8db9097803a5e7771b8e1fd58679d8838515084fa508eb896e1de32dcc

test:
  secret_key_base: e3f5dbd007a38a1e8dbabc303758861c15e2095aa3ab81a46a7821c0ab9cd0cd0b19666193408b131e2d9b00b1375825d6ba85aeac49e7feddd9a47b476d9322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
